backend:
  name: git-gateway
  repo: micronutrientsupport/micronutrient.support
  branch: main
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "_site/images/uploads"
collections:
  - name: posts
    identifier_field: name
    folder: "/"
    create: true
    label: 'Posts'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "sections", widget: "markdown"}